[package]
name = "blog-service"
version = "0.1.0"
authors = ["WaylonCoffee <waylon_coffee@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
